#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 2
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym_identifier = 1,
  anon_sym_LF = 2,
  anon_sym_PIPE = 3,
  sym_comment = 4,
  anon_sym_COLON = 5,
  anon_sym_a = 6,
  anon_sym_b = 7,
  anon_sym_s = 8,
  anon_sym_t = 9,
  anon_sym_v = 10,
  anon_sym_w = 11,
  anon_sym_let = 12,
  anon_sym_EQ = 13,
  anon_sym_unlet = 14,
  anon_sym_call = 15,
  anon_sym_echo = 16,
  anon_sym_return = 17,
  anon_sym_function = 18,
  anon_sym_end = 19,
  anon_sym_endfunction = 20,
  anon_sym_LPAREN = 21,
  anon_sym_COMMA = 22,
  anon_sym_RPAREN = 23,
  sym_bang = 24,
  sym_string_literal = 25,
  sym_float_literal = 26,
  sym_integer_literal = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  sym_script_file = 30,
  sym__cmd_separator = 31,
  sym__statement = 32,
  sym_scoped_identifier = 33,
  sym__ident = 34,
  sym_scope = 35,
  sym_let_statement = 36,
  sym_unlet_statement = 37,
  sym_call_statement = 38,
  sym_echo_statement = 39,
  sym_command = 40,
  sym_function_definition = 41,
  sym_function_declaration = 42,
  sym_function_call = 43,
  sym_parameters = 44,
  sym__expression = 45,
  sym_list = 46,
  aux_sym_script_file_repeat1 = 47,
  aux_sym_echo_statement_repeat1 = 48,
  aux_sym_command_repeat1 = 49,
  aux_sym_parameters_repeat1 = 50,
  aux_sym_list_repeat1 = 51,
  alias_sym_arguments = 52,
  alias_sym_command_name = 53,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LF] = "\n",
  [anon_sym_PIPE] = "|",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_a] = "a",
  [anon_sym_b] = "b",
  [anon_sym_s] = "s",
  [anon_sym_t] = "t",
  [anon_sym_v] = "v",
  [anon_sym_w] = "w",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_unlet] = "unlet",
  [anon_sym_call] = "call",
  [anon_sym_echo] = "echo",
  [anon_sym_return] = "return",
  [anon_sym_function] = "function",
  [anon_sym_end] = "end",
  [anon_sym_endfunction] = "endfunction",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_bang] = "bang",
  [sym_string_literal] = "string_literal",
  [sym_float_literal] = "float_literal",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_script_file] = "script_file",
  [sym__cmd_separator] = "_cmd_separator",
  [sym__statement] = "_statement",
  [sym_scoped_identifier] = "scoped_identifier",
  [sym__ident] = "_ident",
  [sym_scope] = "scope",
  [sym_let_statement] = "let_statement",
  [sym_unlet_statement] = "unlet_statement",
  [sym_call_statement] = "call_statement",
  [sym_echo_statement] = "echo_statement",
  [sym_command] = "command",
  [sym_function_definition] = "function_definition",
  [sym_function_declaration] = "function_declaration",
  [sym_function_call] = "function_call",
  [sym_parameters] = "parameters",
  [sym__expression] = "_expression",
  [sym_list] = "list",
  [aux_sym_script_file_repeat1] = "script_file_repeat1",
  [aux_sym_echo_statement_repeat1] = "echo_statement_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [alias_sym_arguments] = "arguments",
  [alias_sym_command_name] = "command_name",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_a] = anon_sym_a,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_v] = anon_sym_v,
  [anon_sym_w] = anon_sym_w,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_unlet] = anon_sym_unlet,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_echo] = anon_sym_echo,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_endfunction] = anon_sym_endfunction,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_bang] = sym_bang,
  [sym_string_literal] = sym_string_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_script_file] = sym_script_file,
  [sym__cmd_separator] = sym__cmd_separator,
  [sym__statement] = sym__statement,
  [sym_scoped_identifier] = sym_scoped_identifier,
  [sym__ident] = sym__ident,
  [sym_scope] = sym_scope,
  [sym_let_statement] = sym_let_statement,
  [sym_unlet_statement] = sym_unlet_statement,
  [sym_call_statement] = sym_call_statement,
  [sym_echo_statement] = sym_echo_statement,
  [sym_command] = sym_command,
  [sym_function_definition] = sym_function_definition,
  [sym_function_declaration] = sym_function_declaration,
  [sym_function_call] = sym_function_call,
  [sym_parameters] = sym_parameters,
  [sym__expression] = sym__expression,
  [sym_list] = sym_list,
  [aux_sym_script_file_repeat1] = aux_sym_script_file_repeat1,
  [aux_sym_echo_statement_repeat1] = aux_sym_echo_statement_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [alias_sym_arguments] = alias_sym_arguments,
  [alias_sym_command_name] = alias_sym_command_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unlet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_echo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfunction] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_bang] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_script_file] = {
    .visible = true,
    .named = true,
  },
  [sym__cmd_separator] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_scoped_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_unlet_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_call_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_script_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_echo_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_command_name] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_arguments = 1,
  field_function = 2,
  field_name = 3,
  field_parameters = 4,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[5] = {
  [3] = {.index = 0, .length = 2},
  [4] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_function, 0},
  [2] =
    {field_name, 0},
    {field_parameters, 1},
};

static TSSymbol ts_alias_sequences[5][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_command_name,
  },
  [2] = {
    [0] = alias_sym_command_name,
    [1] = alias_sym_arguments,
  },
  [3] = {
    [1] = alias_sym_arguments,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(18);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '|') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '|') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(26);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_bang);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(25);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(5);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(25);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == 'v') ADVANCE(11);
      if (lookahead == 'w') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym_a);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_echo);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_unlet);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_endfunction);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_a] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_unlet] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_echo] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_endfunction] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_bang] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_script_file] = STATE(116),
    [sym__statement] = STATE(23),
    [sym_let_statement] = STATE(23),
    [sym_unlet_statement] = STATE(23),
    [sym_call_statement] = STATE(23),
    [sym_echo_statement] = STATE(23),
    [sym_command] = STATE(23),
    [sym_function_definition] = STATE(23),
    [aux_sym_script_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_unlet] = ACTIONS(9),
    [anon_sym_call] = ACTIONS(11),
    [anon_sym_echo] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LF,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    STATE(59), 1,
      sym__cmd_separator,
    STATE(119), 1,
      sym_scope,
    ACTIONS(21), 2,
      anon_sym_PIPE,
      sym_comment,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(25), 3,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
    STATE(6), 4,
      sym_function_call,
      sym__expression,
      sym_list,
      aux_sym_echo_statement_repeat1,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [43] = 10,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LF,
    STATE(53), 1,
      sym__cmd_separator,
    STATE(119), 1,
      sym_scope,
    ACTIONS(31), 2,
      anon_sym_PIPE,
      sym_comment,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(25), 3,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
    STATE(6), 4,
      sym_function_call,
      sym__expression,
      sym_list,
      aux_sym_echo_statement_repeat1,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [86] = 10,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LF,
    STATE(61), 1,
      sym__cmd_separator,
    STATE(119), 1,
      sym_scope,
    ACTIONS(35), 2,
      anon_sym_PIPE,
      sym_comment,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(37), 3,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
    STATE(2), 4,
      sym_function_call,
      sym__expression,
      sym_list,
      aux_sym_echo_statement_repeat1,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [129] = 10,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LF,
    STATE(51), 1,
      sym__cmd_separator,
    STATE(119), 1,
      sym_scope,
    ACTIONS(41), 2,
      anon_sym_PIPE,
      sym_comment,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(43), 3,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
    STATE(3), 4,
      sym_function_call,
      sym__expression,
      sym_list,
      aux_sym_echo_statement_repeat1,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [172] = 9,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(48), 1,
      anon_sym_LF,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    STATE(119), 1,
      sym_scope,
    ACTIONS(50), 2,
      anon_sym_PIPE,
      sym_comment,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(55), 3,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
    STATE(6), 4,
      sym_function_call,
      sym__expression,
      sym_list,
      aux_sym_echo_statement_repeat1,
    ACTIONS(52), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [212] = 9,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_string_literal,
    ACTIONS(67), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
    STATE(117), 1,
      sym_scope,
    ACTIONS(65), 2,
      sym_float_literal,
      sym_integer_literal,
    STATE(76), 2,
      sym_scoped_identifier,
      sym__ident,
    STATE(102), 3,
      sym_function_call,
      sym__expression,
      sym_list,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [249] = 9,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_LBRACK,
    ACTIONS(71), 1,
      sym_string_literal,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    STATE(117), 1,
      sym_scope,
    ACTIONS(73), 2,
      sym_float_literal,
      sym_integer_literal,
    STATE(76), 2,
      sym_scoped_identifier,
      sym__ident,
    STATE(92), 3,
      sym_function_call,
      sym__expression,
      sym_list,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [286] = 8,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(77), 1,
      sym_string_literal,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    STATE(119), 1,
      sym_scope,
    ACTIONS(79), 2,
      sym_float_literal,
      sym_integer_literal,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    STATE(89), 3,
      sym_function_call,
      sym__expression,
      sym_list,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [320] = 8,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      sym_string_literal,
    STATE(119), 1,
      sym_scope,
    ACTIONS(85), 2,
      sym_float_literal,
      sym_integer_literal,
    STATE(16), 2,
      sym_scoped_identifier,
      sym__ident,
    STATE(86), 3,
      sym_function_call,
      sym__expression,
      sym_list,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [354] = 8,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_LBRACK,
    ACTIONS(87), 1,
      sym_string_literal,
    STATE(117), 1,
      sym_scope,
    ACTIONS(89), 2,
      sym_float_literal,
      sym_integer_literal,
    STATE(76), 2,
      sym_scoped_identifier,
      sym__ident,
    STATE(108), 3,
      sym_function_call,
      sym__expression,
      sym_list,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [388] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(103), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(20), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [421] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(105), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(21), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [454] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(107), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(21), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [487] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(109), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(21), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [520] = 4,
    ACTIONS(113), 1,
      anon_sym_LF,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_parameters,
    ACTIONS(111), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [545] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(109), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(14), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [578] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(117), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(15), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [611] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(119), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(13), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [644] = 8,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_let,
    ACTIONS(95), 1,
      anon_sym_unlet,
    ACTIONS(97), 1,
      anon_sym_call,
    ACTIONS(99), 1,
      anon_sym_echo,
    ACTIONS(101), 1,
      anon_sym_function,
    ACTIONS(119), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(21), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [677] = 8,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(124), 1,
      anon_sym_let,
    ACTIONS(127), 1,
      anon_sym_unlet,
    ACTIONS(130), 1,
      anon_sym_call,
    ACTIONS(133), 1,
      anon_sym_echo,
    ACTIONS(136), 1,
      anon_sym_function,
    ACTIONS(139), 2,
      anon_sym_end,
      anon_sym_endfunction,
    STATE(21), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [710] = 2,
    ACTIONS(143), 1,
      anon_sym_LF,
    ACTIONS(141), 14,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      anon_sym_LPAREN,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [730] = 8,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_unlet,
    ACTIONS(11), 1,
      anon_sym_call,
    ACTIONS(13), 1,
      anon_sym_echo,
    ACTIONS(15), 1,
      anon_sym_function,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    STATE(24), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [762] = 8,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(152), 1,
      anon_sym_let,
    ACTIONS(155), 1,
      anon_sym_unlet,
    ACTIONS(158), 1,
      anon_sym_call,
    ACTIONS(161), 1,
      anon_sym_echo,
    ACTIONS(164), 1,
      anon_sym_function,
    STATE(24), 8,
      sym__statement,
      sym_let_statement,
      sym_unlet_statement,
      sym_call_statement,
      sym_echo_statement,
      sym_command,
      sym_function_definition,
      aux_sym_script_file_repeat1,
  [794] = 2,
    ACTIONS(169), 1,
      anon_sym_LF,
    ACTIONS(167), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [813] = 2,
    ACTIONS(173), 1,
      anon_sym_LF,
    ACTIONS(171), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [832] = 2,
    ACTIONS(177), 1,
      anon_sym_LF,
    ACTIONS(175), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [851] = 2,
    ACTIONS(181), 1,
      anon_sym_LF,
    ACTIONS(179), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [870] = 2,
    ACTIONS(185), 1,
      anon_sym_LF,
    ACTIONS(183), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [889] = 2,
    ACTIONS(189), 1,
      anon_sym_LF,
    ACTIONS(187), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [908] = 2,
    ACTIONS(193), 1,
      anon_sym_LF,
    ACTIONS(191), 13,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
      sym_string_literal,
      sym_float_literal,
      sym_integer_literal,
      anon_sym_LBRACK,
  [927] = 6,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_bang,
    STATE(79), 1,
      sym_function_declaration,
    STATE(117), 1,
      sym_scope,
    STATE(107), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [952] = 6,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(199), 1,
      sym_bang,
    STATE(83), 1,
      sym_function_declaration,
    STATE(117), 1,
      sym_scope,
    STATE(107), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [977] = 5,
    ACTIONS(201), 1,
      sym_identifier,
    STATE(82), 1,
      sym_function_call,
    STATE(117), 1,
      sym_scope,
    STATE(114), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [999] = 5,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(205), 1,
      sym_bang,
    STATE(119), 1,
      sym_scope,
    STATE(73), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1021] = 5,
    ACTIONS(201), 1,
      sym_identifier,
    STATE(74), 1,
      sym_function_call,
    STATE(117), 1,
      sym_scope,
    STATE(114), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1043] = 5,
    ACTIONS(207), 1,
      sym_identifier,
    ACTIONS(209), 1,
      sym_bang,
    STATE(119), 1,
      sym_scope,
    STATE(81), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1065] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(78), 1,
      sym_function_declaration,
    STATE(117), 1,
      sym_scope,
    STATE(107), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1087] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(85), 1,
      sym_function_declaration,
    STATE(117), 1,
      sym_scope,
    STATE(107), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1109] = 4,
    ACTIONS(211), 1,
      sym_identifier,
    STATE(117), 1,
      sym_scope,
    STATE(118), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1128] = 4,
    ACTIONS(213), 1,
      sym_identifier,
    STATE(117), 1,
      sym_scope,
    STATE(122), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1147] = 4,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(119), 1,
      sym_scope,
    STATE(80), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1166] = 4,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(119), 1,
      sym_scope,
    STATE(84), 2,
      sym_scoped_identifier,
      sym__ident,
    ACTIONS(23), 6,
      anon_sym_a,
      anon_sym_b,
      anon_sym_s,
      anon_sym_t,
      anon_sym_v,
      anon_sym_w,
  [1185] = 1,
    ACTIONS(219), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1196] = 1,
    ACTIONS(221), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1207] = 1,
    ACTIONS(223), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1218] = 1,
    ACTIONS(225), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1229] = 1,
    ACTIONS(227), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1240] = 1,
    ACTIONS(229), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1251] = 1,
    ACTIONS(231), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1262] = 1,
    ACTIONS(233), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1273] = 1,
    ACTIONS(235), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1284] = 1,
    ACTIONS(237), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1295] = 1,
    ACTIONS(239), 8,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
      anon_sym_end,
      anon_sym_endfunction,
  [1306] = 2,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
    ACTIONS(231), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1318] = 2,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1330] = 2,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    ACTIONS(219), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1342] = 2,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    ACTIONS(223), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1354] = 2,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    ACTIONS(237), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1366] = 2,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1378] = 2,
    ACTIONS(253), 1,
      ts_builtin_sym_end,
    ACTIONS(233), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1390] = 2,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(229), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1402] = 2,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    ACTIONS(227), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1414] = 2,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    ACTIONS(235), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1426] = 2,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
    ACTIONS(239), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_unlet,
      anon_sym_call,
      anon_sym_echo,
      anon_sym_function,
  [1438] = 5,
    ACTIONS(263), 1,
      sym_identifier,
    ACTIONS(265), 1,
      anon_sym_LF,
    STATE(58), 1,
      sym__cmd_separator,
    STATE(68), 1,
      aux_sym_command_repeat1,
    ACTIONS(267), 2,
      anon_sym_PIPE,
      sym_comment,
  [1455] = 5,
    ACTIONS(263), 1,
      sym_identifier,
    ACTIONS(269), 1,
      anon_sym_LF,
    STATE(46), 1,
      sym__cmd_separator,
    STATE(69), 1,
      aux_sym_command_repeat1,
    ACTIONS(271), 2,
      anon_sym_PIPE,
      sym_comment,
  [1472] = 5,
    ACTIONS(263), 1,
      sym_identifier,
    ACTIONS(273), 1,
      anon_sym_LF,
    STATE(63), 1,
      sym__cmd_separator,
    STATE(70), 1,
      aux_sym_command_repeat1,
    ACTIONS(275), 2,
      anon_sym_PIPE,
      sym_comment,
  [1489] = 5,
    ACTIONS(263), 1,
      sym_identifier,
    ACTIONS(277), 1,
      anon_sym_LF,
    STATE(48), 1,
      sym__cmd_separator,
    STATE(70), 1,
      aux_sym_command_repeat1,
    ACTIONS(279), 2,
      anon_sym_PIPE,
      sym_comment,
  [1506] = 4,
    ACTIONS(281), 1,
      sym_identifier,
    ACTIONS(284), 1,
      anon_sym_LF,
    STATE(70), 1,
      aux_sym_command_repeat1,
    ACTIONS(286), 2,
      anon_sym_PIPE,
      sym_comment,
  [1520] = 3,
    ACTIONS(288), 1,
      anon_sym_LF,
    STATE(64), 1,
      sym__cmd_separator,
    ACTIONS(290), 2,
      anon_sym_PIPE,
      sym_comment,
  [1531] = 1,
    ACTIONS(143), 4,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1538] = 3,
    ACTIONS(292), 1,
      anon_sym_LF,
    STATE(50), 1,
      sym__cmd_separator,
    ACTIONS(294), 2,
      anon_sym_PIPE,
      sym_comment,
  [1549] = 3,
    ACTIONS(296), 1,
      anon_sym_LF,
    STATE(45), 1,
      sym__cmd_separator,
    ACTIONS(298), 2,
      anon_sym_PIPE,
      sym_comment,
  [1560] = 3,
    ACTIONS(300), 1,
      anon_sym_LF,
    STATE(65), 1,
      sym__cmd_separator,
    ACTIONS(302), 2,
      anon_sym_PIPE,
      sym_comment,
  [1571] = 3,
    ACTIONS(304), 1,
      anon_sym_LPAREN,
    STATE(115), 1,
      sym_parameters,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1582] = 2,
    ACTIONS(308), 1,
      anon_sym_LF,
    ACTIONS(306), 3,
      anon_sym_PIPE,
      sym_comment,
      sym_identifier,
  [1591] = 3,
    ACTIONS(310), 1,
      anon_sym_LF,
    STATE(17), 1,
      sym__cmd_separator,
    ACTIONS(312), 2,
      anon_sym_PIPE,
      sym_comment,
  [1602] = 3,
    ACTIONS(314), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym__cmd_separator,
    ACTIONS(316), 2,
      anon_sym_PIPE,
      sym_comment,
  [1613] = 3,
    ACTIONS(318), 1,
      anon_sym_LF,
    STATE(44), 1,
      sym__cmd_separator,
    ACTIONS(320), 2,
      anon_sym_PIPE,
      sym_comment,
  [1624] = 3,
    ACTIONS(322), 1,
      anon_sym_LF,
    STATE(55), 1,
      sym__cmd_separator,
    ACTIONS(324), 2,
      anon_sym_PIPE,
      sym_comment,
  [1635] = 3,
    ACTIONS(326), 1,
      anon_sym_LF,
    STATE(60), 1,
      sym__cmd_separator,
    ACTIONS(328), 2,
      anon_sym_PIPE,
      sym_comment,
  [1646] = 3,
    ACTIONS(330), 1,
      anon_sym_LF,
    STATE(12), 1,
      sym__cmd_separator,
    ACTIONS(332), 2,
      anon_sym_PIPE,
      sym_comment,
  [1657] = 3,
    ACTIONS(334), 1,
      anon_sym_LF,
    STATE(57), 1,
      sym__cmd_separator,
    ACTIONS(336), 2,
      anon_sym_PIPE,
      sym_comment,
  [1668] = 3,
    ACTIONS(338), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym__cmd_separator,
    ACTIONS(340), 2,
      anon_sym_PIPE,
      sym_comment,
  [1679] = 3,
    ACTIONS(342), 1,
      anon_sym_LF,
    STATE(47), 1,
      sym__cmd_separator,
    ACTIONS(344), 2,
      anon_sym_PIPE,
      sym_comment,
  [1690] = 3,
    ACTIONS(346), 1,
      anon_sym_LF,
    STATE(62), 1,
      sym__cmd_separator,
    ACTIONS(348), 2,
      anon_sym_PIPE,
      sym_comment,
  [1701] = 3,
    ACTIONS(350), 1,
      anon_sym_LF,
    STATE(54), 1,
      sym__cmd_separator,
    ACTIONS(352), 2,
      anon_sym_PIPE,
      sym_comment,
  [1712] = 3,
    ACTIONS(354), 1,
      anon_sym_LF,
    STATE(56), 1,
      sym__cmd_separator,
    ACTIONS(356), 2,
      anon_sym_PIPE,
      sym_comment,
  [1723] = 3,
    ACTIONS(358), 1,
      anon_sym_LF,
    STATE(52), 1,
      sym__cmd_separator,
    ACTIONS(360), 2,
      anon_sym_PIPE,
      sym_comment,
  [1734] = 3,
    ACTIONS(362), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym__cmd_separator,
    ACTIONS(364), 2,
      anon_sym_PIPE,
      sym_comment,
  [1745] = 3,
    ACTIONS(366), 1,
      anon_sym_COMMA,
    ACTIONS(368), 1,
      anon_sym_RBRACK,
    STATE(94), 1,
      aux_sym_list_repeat1,
  [1755] = 3,
    ACTIONS(370), 1,
      anon_sym_COMMA,
    ACTIONS(372), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_parameters_repeat1,
  [1765] = 3,
    ACTIONS(366), 1,
      anon_sym_COMMA,
    ACTIONS(374), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      aux_sym_list_repeat1,
  [1775] = 3,
    ACTIONS(370), 1,
      anon_sym_COMMA,
    ACTIONS(376), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameters_repeat1,
  [1785] = 3,
    ACTIONS(370), 1,
      anon_sym_COMMA,
    ACTIONS(378), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_parameters_repeat1,
  [1795] = 3,
    ACTIONS(370), 1,
      anon_sym_COMMA,
    ACTIONS(380), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_parameters_repeat1,
  [1805] = 3,
    ACTIONS(382), 1,
      anon_sym_COMMA,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_parameters_repeat1,
  [1815] = 3,
    ACTIONS(387), 1,
      anon_sym_COMMA,
    ACTIONS(390), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      aux_sym_list_repeat1,
  [1825] = 2,
    ACTIONS(392), 1,
      anon_sym_LF,
    ACTIONS(394), 2,
      anon_sym_PIPE,
      sym_comment,
  [1833] = 3,
    ACTIONS(366), 1,
      anon_sym_COMMA,
    ACTIONS(396), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      aux_sym_list_repeat1,
  [1843] = 3,
    ACTIONS(366), 1,
      anon_sym_COMMA,
    ACTIONS(398), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      aux_sym_list_repeat1,
  [1853] = 2,
    ACTIONS(400), 1,
      sym_identifier,
    ACTIONS(402), 1,
      anon_sym_RPAREN,
  [1860] = 1,
    ACTIONS(385), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1865] = 1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1870] = 1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1875] = 2,
    ACTIONS(404), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      sym_parameters,
  [1882] = 1,
    ACTIONS(390), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1887] = 2,
    ACTIONS(406), 1,
      sym_identifier,
    ACTIONS(408), 1,
      anon_sym_RPAREN,
  [1894] = 1,
    ACTIONS(177), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1899] = 1,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1904] = 1,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1909] = 1,
    ACTIONS(173), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1914] = 2,
    ACTIONS(404), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_parameters,
  [1921] = 1,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1926] = 1,
    ACTIONS(410), 1,
      ts_builtin_sym_end,
  [1930] = 1,
    ACTIONS(412), 1,
      anon_sym_COLON,
  [1934] = 1,
    ACTIONS(414), 1,
      anon_sym_EQ,
  [1938] = 1,
    ACTIONS(416), 1,
      anon_sym_COLON,
  [1942] = 1,
    ACTIONS(418), 1,
      sym_identifier,
  [1946] = 1,
    ACTIONS(420), 1,
      sym_identifier,
  [1950] = 1,
    ACTIONS(422), 1,
      anon_sym_EQ,
  [1954] = 1,
    ACTIONS(424), 1,
      anon_sym_COLON,
  [1958] = 1,
    ACTIONS(426), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 172,
  [SMALL_STATE(7)] = 212,
  [SMALL_STATE(8)] = 249,
  [SMALL_STATE(9)] = 286,
  [SMALL_STATE(10)] = 320,
  [SMALL_STATE(11)] = 354,
  [SMALL_STATE(12)] = 388,
  [SMALL_STATE(13)] = 421,
  [SMALL_STATE(14)] = 454,
  [SMALL_STATE(15)] = 487,
  [SMALL_STATE(16)] = 520,
  [SMALL_STATE(17)] = 545,
  [SMALL_STATE(18)] = 578,
  [SMALL_STATE(19)] = 611,
  [SMALL_STATE(20)] = 644,
  [SMALL_STATE(21)] = 677,
  [SMALL_STATE(22)] = 710,
  [SMALL_STATE(23)] = 730,
  [SMALL_STATE(24)] = 762,
  [SMALL_STATE(25)] = 794,
  [SMALL_STATE(26)] = 813,
  [SMALL_STATE(27)] = 832,
  [SMALL_STATE(28)] = 851,
  [SMALL_STATE(29)] = 870,
  [SMALL_STATE(30)] = 889,
  [SMALL_STATE(31)] = 908,
  [SMALL_STATE(32)] = 927,
  [SMALL_STATE(33)] = 952,
  [SMALL_STATE(34)] = 977,
  [SMALL_STATE(35)] = 999,
  [SMALL_STATE(36)] = 1021,
  [SMALL_STATE(37)] = 1043,
  [SMALL_STATE(38)] = 1065,
  [SMALL_STATE(39)] = 1087,
  [SMALL_STATE(40)] = 1109,
  [SMALL_STATE(41)] = 1128,
  [SMALL_STATE(42)] = 1147,
  [SMALL_STATE(43)] = 1166,
  [SMALL_STATE(44)] = 1185,
  [SMALL_STATE(45)] = 1196,
  [SMALL_STATE(46)] = 1207,
  [SMALL_STATE(47)] = 1218,
  [SMALL_STATE(48)] = 1229,
  [SMALL_STATE(49)] = 1240,
  [SMALL_STATE(50)] = 1251,
  [SMALL_STATE(51)] = 1262,
  [SMALL_STATE(52)] = 1273,
  [SMALL_STATE(53)] = 1284,
  [SMALL_STATE(54)] = 1295,
  [SMALL_STATE(55)] = 1306,
  [SMALL_STATE(56)] = 1318,
  [SMALL_STATE(57)] = 1330,
  [SMALL_STATE(58)] = 1342,
  [SMALL_STATE(59)] = 1354,
  [SMALL_STATE(60)] = 1366,
  [SMALL_STATE(61)] = 1378,
  [SMALL_STATE(62)] = 1390,
  [SMALL_STATE(63)] = 1402,
  [SMALL_STATE(64)] = 1414,
  [SMALL_STATE(65)] = 1426,
  [SMALL_STATE(66)] = 1438,
  [SMALL_STATE(67)] = 1455,
  [SMALL_STATE(68)] = 1472,
  [SMALL_STATE(69)] = 1489,
  [SMALL_STATE(70)] = 1506,
  [SMALL_STATE(71)] = 1520,
  [SMALL_STATE(72)] = 1531,
  [SMALL_STATE(73)] = 1538,
  [SMALL_STATE(74)] = 1549,
  [SMALL_STATE(75)] = 1560,
  [SMALL_STATE(76)] = 1571,
  [SMALL_STATE(77)] = 1582,
  [SMALL_STATE(78)] = 1591,
  [SMALL_STATE(79)] = 1602,
  [SMALL_STATE(80)] = 1613,
  [SMALL_STATE(81)] = 1624,
  [SMALL_STATE(82)] = 1635,
  [SMALL_STATE(83)] = 1646,
  [SMALL_STATE(84)] = 1657,
  [SMALL_STATE(85)] = 1668,
  [SMALL_STATE(86)] = 1679,
  [SMALL_STATE(87)] = 1690,
  [SMALL_STATE(88)] = 1701,
  [SMALL_STATE(89)] = 1712,
  [SMALL_STATE(90)] = 1723,
  [SMALL_STATE(91)] = 1734,
  [SMALL_STATE(92)] = 1745,
  [SMALL_STATE(93)] = 1755,
  [SMALL_STATE(94)] = 1765,
  [SMALL_STATE(95)] = 1775,
  [SMALL_STATE(96)] = 1785,
  [SMALL_STATE(97)] = 1795,
  [SMALL_STATE(98)] = 1805,
  [SMALL_STATE(99)] = 1815,
  [SMALL_STATE(100)] = 1825,
  [SMALL_STATE(101)] = 1833,
  [SMALL_STATE(102)] = 1843,
  [SMALL_STATE(103)] = 1853,
  [SMALL_STATE(104)] = 1860,
  [SMALL_STATE(105)] = 1865,
  [SMALL_STATE(106)] = 1870,
  [SMALL_STATE(107)] = 1875,
  [SMALL_STATE(108)] = 1882,
  [SMALL_STATE(109)] = 1887,
  [SMALL_STATE(110)] = 1894,
  [SMALL_STATE(111)] = 1899,
  [SMALL_STATE(112)] = 1904,
  [SMALL_STATE(113)] = 1909,
  [SMALL_STATE(114)] = 1914,
  [SMALL_STATE(115)] = 1921,
  [SMALL_STATE(116)] = 1926,
  [SMALL_STATE(117)] = 1930,
  [SMALL_STATE(118)] = 1934,
  [SMALL_STATE(119)] = 1938,
  [SMALL_STATE(120)] = 1942,
  [SMALL_STATE(121)] = 1946,
  [SMALL_STATE(122)] = 1950,
  [SMALL_STATE(123)] = 1954,
  [SMALL_STATE(124)] = 1958,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_statement_repeat1, 2), SHIFT_REPEAT(16),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_echo_statement_repeat1, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_echo_statement_repeat1, 2),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_statement_repeat1, 2), SHIFT_REPEAT(123),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_statement_repeat1, 2), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_statement_repeat1, 2), SHIFT_REPEAT(7),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(67),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(40),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(35),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(36),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(5),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(32),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scoped_identifier, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_identifier, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_file, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_script_file_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(66),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(41),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(37),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(34),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(4),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_file_repeat1, 2), SHIFT_REPEAT(33),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, .production_id = 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, .production_id = 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 4),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unlet_statement, 4),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_statement, 3),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, .production_id = 1),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3, .production_id = 2),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unlet_statement, 3),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 2),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 3),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unlet_statement, 3),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unlet_statement, 4),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_statement, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, .production_id = 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [281] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(77),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [336] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [340] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [348] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [352] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [356] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [360] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [364] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [382] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(120),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [387] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(11),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 2, .production_id = 4),
  [394] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 2, .production_id = 4),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [410] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [424] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 1),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_VimL(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
